pipelines:
  branches:
    main:
      - step:
          name: deploy
          script:
            - curl -X GET "https://jenkins.alexsim.co.uk/job/Alex%20Sim%20WP/job/Alex%20Sim%20WP/build?token=${JENKINS_ACCESS_TOKEN}"